### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by jasonyork** [philhawthorne/docker-influxdb-grafana#35] opened 2020-04-08 01:01 UTC
Hi Phil,

I'm trying to get started with influxdb and having trouble getting this container to start up.  Using the quick start command:
```
docker run -d \
  --name docker-influxdb-grafana \
  -p 3003:3003 \
  -p 3004:8083 \
  -p 8086:8086 \
  -v /path/for/influxdb:/var/lib/influxdb \
  -v /path/for/grafana:/var/lib/grafana \
  philhawthorne/docker-influxdb-grafana:latest
```
(except changing the paths for my system)

I get the following output from `docker logs`.  Any ideas?

> /usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2020-04-08 00:24:47,220 CRIT Supervisor running as root (no user in config file)
2020-04-08 00:24:47,221 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2020-04-08 00:24:47,233 INFO RPC interface 'supervisor' initialized
2020-04-08 00:24:47,233 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-04-08 00:24:47,233 INFO supervisord started with pid 1
2020-04-08 00:24:48,239 INFO spawned: 'chronograf' with pid 10
2020-04-08 00:24:48,245 INFO spawned: 'influxdb' with pid 11
2020-04-08 00:24:48,248 INFO spawned: 'grafana' with pid 12
2020-04-08 00:24:49,315 INFO success: chronograf entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-08 00:24:49,315 INFO success: influxdb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-08 00:24:49,315 INFO success: grafana entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-08 00:24:49,326 INFO exited: influxdb (exit status 1; not expected)
2020-04-08 00:24:49,359 INFO spawned: 'influxdb' with pid 74
2020-04-08 00:24:50,382 INFO success: influxdb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-08 00:24:50,462 INFO reaped unknown pid 83
2020-04-08 00:24:55,393 INFO exited: influxdb (exit status 0; expected)
2020-04-08 00:25:00,398 INFO exited: grafana (exit status 1; not expected)
2020-04-08 00:25:01,402 INFO spawned: 'grafana' with pid 147
2020-04-08 00:25:01,420 INFO exited: grafana (exit status 0; not expected)
2020-04-08 00:25:02,430 INFO spawned: 'grafana' with pid 153
2020-04-08 00:25:02,447 INFO exited: grafana (exit status 0; not expected)
2020-04-08 00:25:04,458 INFO spawned: 'grafana' with pid 159
2020-04-08 00:25:04,476 INFO exited: grafana (exit status 0; not expected)
2020-04-08 00:25:07,484 INFO spawned: 'grafana' with pid 165
2020-04-08 00:25:07,501 INFO exited: grafana (exit status 0; not expected)
2020-04-08 00:25:08,508 INFO gave up: grafana entered FATAL state, too many start retries too quickly

**Comment by zerog2k** [comment] 2020-04-10 03:33
yeah i have been having strange problems with this (using `edge` tag, but same issue)
usually happens after host reboot
a few observations... my local influxdb persistant store dir (`~/.influxdb/`) keeps getting owned by root user instead of my user (not sure why, but this seem related.)

Also noticed that if you examine the container there is an assumption that supervisord is managing all of the processes, and if you examine w/ supervisorctl,  it seems like grafana-server may be getting launched separately (systemd?), and it says influxdb exited, but it appears to be running.

```
UID | PID | PPID | C | STIME | TTY | TIME | CMD
-- | -- | -- | -- | -- | -- | -- | --
root | 6979 | 6961 | 0 | 22:22 | ? | 00:00:01 | /usr/bin/python /usr/bin/supervisord
root | 7062 | 6979 | 2 | 22:22 | ? | 00:00:12 | /usr/bin/chronograf start --port=8083
root | 7084 | 6979 | 6 | 22:22 | ? | 00:00:37 | /usr/bin/influxd -pidfile /var/run/influxdb/influxd.pid -config /etc/influxdb/influxdb.conf
systemd+ | 7097 | 6979 | 0 | 22:22 | ? | 00:00:00 | /usr/sbin/grafana-server --pidfile=/var/run/grafana-server.pid --config=/etc/grafana/grafana.ini --packaging=deb cfg:default.paths.provisioning=/etc/grafana/provisioning cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins
```

**Comment by corymosiman12** [comment] 2020-04-10 17:43
Also similar questions.  The strange thing, however, is that I can still access grafana at localhost:3003.  Is that the same behavior for others?

**Comment by zerog2k** [comment] 2020-04-10 18:10
I looked at it a bit more last night, and what I noticed was that neither grafana nor influxdb is being directly managed by supervisord, instead supervisord is launching them via init scripts, so supervisord maybe thinks they have failed? But it seems to sometimes work, so the next thought/observation was that when manually starting these up in the container outside of supervisorctl, I see that `service influxdb start` says it failed to start, and then `service influxdb status` will return failed status for several seconds afterwards, before eventually returning success. So I think there is some delay in influxdb startup (perhaps with lots of data?)
Perhaps this is why in supervisord conf, there is the:
```
/etc/init.d/influxdb start && sleep 5
```
maybe this sleep needs to be longer?

**Comment by zerog2k** [comment] 2020-04-10 18:15
I think that the first command (influxdb start) is returning non-zero exit code here:
https://github.com/philhawthorne/docker-influxdb-grafana/blob/master/influxdb/init.sh#L125-L137
and this may be due to influxdb taking some time to start.. Perhaps supervisord detects this "failure" and continues to try to start multiple times.

Grafana-server is actually started because it's daemonized by the init script:
https://github.com/philhawthorne/docker-influxdb-grafana/blob/master/supervisord/supervisord.conf#L14
rather than being "supervised" directly by supervisord.

I'm not sure if everything should be directly supervised, but maybe a short term fix could be to have the influxdb start script wait a bit longer, or have supervisord fire influxdb `start` action, then blindly wait for 5-10 seconds before doing influxdb `status` action to test... if _this_ fails, then supervisord should attempt process restarts.

**Comment by zerog2k** [comment] 2020-04-10 18:17
here is an alternative supervisord configuration example (untested with recent influxdb/grafana) which controls the processes directly (rather than relying upon initscripts):
https://github.com/roman-vynar/grafana-prometheus-influx.docker/blob/master/monitor/supervisord.conf#L10-L20

**Comment by zerog2k** [comment] 2020-04-11 15:30
maybe folks here with issues can give `philhawthorne/docker-influxdb-grafana:edge` a try, as it has the changes from `dev` branch

**Comment by jasonyork** [comment] 2020-04-12 02:20
@zerog2k - Just tried the `edge` container and seems to start up fine.  I'm also able to browse to the UI.  Thanks!

**Comment by philhawthorne** [comment] 2020-04-12 04:01
Thanks everyone!

With this confirmed I'm going to merge this to master now and close this.

Thanks again @zerog2k

**Closed as completed by philhawthorne** 2020-04-12 04:01 UTC
